version: '3.8'

services:
  auth_app:
    container_name: auth_app
    image: auth_app:1.0.0
    build:
      context: .
      dockerfile: ./Dockerfile
    command: npm run start:prod
    env_file: .env
    ports:
      - 3333:3333
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4.4
    container_name: mongodb
    ports:
      - 27017:27017
    env_file: .env
